python run_train.py \
--diff_steps 1000 \
--lr 0.0001 \
--learning_steps 50 \
--seed 102 \
--noise_schedule sqrt \
--hidden_dim 128 \
--bsz 100 \
--dataset qqp \
--data_dir "datasets/CommonsenseConversation" \
--vocab bert \
--seq_len 128 \
--schedule_sampler uniform \
--notes test-qqp
